---
- name: Configure ubuntu server
  hosts: all
  become: yes

  tasks:
    - name: Create user for lab activity
      user:
        name: ubuntu
        state: present
        password: "{{ 'Kube101!' | password_hash('sha512') }}"

    - name: Install all the software needed
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - bash-completion
        - vim
        - git
        - curl
        - gnustep-gui-runtime
        - python3-virtualenv
        - python3-pip
    - name: Install other requirements using pip
      pip:
        name: "{{ item }}"
      loop:
        - ansible==4.8.0
        - ansible-core==2.11.6
        - cryptography==2.8
        - jinja2==2.11.3  
        - netaddr==0.7.19
        - pbr==5.4.4
        - jmespath==0.9.5
        - ruamel.yaml==0.16.10
        - ruamel.yaml.clib==0.2.6
        - MarkupSafe==1.1.1
    